### ISSUE TITLE
Phase 4: Create the UML diagram

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#10]

**Comment by mdoussias** [comment]
STATUS: I have half of this done on giffy and the other half done on my computer.  Should be quick to just make the last minute changes before submission tomorrow.  

It's about 90% done, but just waiting for the final submissions to be completed before completing the UML diagram.

**Comment by mdoussias** [comment]
Mostly done.... Jsut 3 methods in phase3

**Comment by mdoussias** [comment]
All done.
