### ISSUE TITLE
playCard in CardGameFramework class

### ISSUE THREAD

**Issue by p12345vls** [team-makeSmart/GUI-Cards#14]
This method calls a **playCard(cardIndex)** method that does not exists in the Hand class, neither in the assignment description. There is a playCard() in Hand without arguments. Apparently, this method should be added in the Hand class.

` Card playCard(int playerIndex, int cardIndex)
   {
      // returns bad card if either argument is bad
      if (playerIndex < 0 ||  playerIndex > numPlayers - 1 ||
          cardIndex < 0 || cardIndex > numCardsPerHand - 1)
      {
         //Creates a card that does not work
         return new Card('M', Card.Suit.SPADES);      
      }
   
      // return the card played
      return hand[playerIndex].**playCard(cardIndex);**
   
   }`

**Comment by Mcghee-Jake** [comment]
Hey so its a little confusing but the playCard method you provided is within the CardGameFramework class that he provided for us. I had to modify the playCard method in the Hand class so that it takes an integer value.

It looks like this now

 /**
    * Returns and removes the card in the top occupied position of the array
    * @parm cardIndex the index of the card that will be played
    * @return the top card
    */
   public Card playCard(int cardIndex)
   {
      Card errorCard = new Card('w', Card.Suit.SPADES);
      if (numCards == 0 || cardIndex < 0 || cardIndex > MAX_CARDS)
         return errorCard;
      Card playCard = myCards[cardIndex];
      removeCard(cardIndex);
      return playCard;
   }
   
   /**
    * Helper method for playCard
    * "Deletes" a carrom the myCards array
    * Note: Since we can't actually change the size of the array, the
    * element is not actually deleted. Instead, the cards in the hand
    * above the cardIndex are shifted to the left once and numCards
    * is decremented once, which effectively deletes the card for 
    * all practical purposes of this application
    * @param cardIndex the index of the card that will be removed
    */
   private void removeCard(int cardIndex) {
	   for (int i = cardIndex; i < numCards-1; i++) 
	   {
		   myCards[i] = myCards[i+1];
	   }
	   numCards--;
   }

**Comment by p12345vls** [comment]
I mean a method  playCard(int cardIndex) should be added in the hand class. This way the existed playCard() method without arguments need no modified. What is confusing?

**Comment by Mcghee-Jake** [comment]
Nothing is confusing. I closed this issue because I updated updated playCard to accept a cardIndex. See my recent pull request
