### ISSUE TITLE
Phase1.Java   turnIntIntoCardValue(int j)

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/GUI-Cards#17]
With time permitting.... This maybe should be refactored to use the array values as is already defined in the CARD class instead of redefining the array in this place.

After a working program is completed, I will refactor this unless someone has an objection?

         //
	 // Turns 0 - 13 into "A", "2", "3", ... "Q", "K", "X"
	 // @param j the corresponding card value in the array index
	 // @return the card value
	 //
	static String turnIntIntoCardValue(int j)
	{
		String values[] = { "A", "2", "3", "4", "5", "6", "7", 
				"8", "9", "T", "J", "Q", "K", "X" };
		return values[j];
	}

**Comment by mdoussias** [comment]
Actually I may be wrong on this... the spec does not say to use the card class, necessarily.

I'll check more tomorrow.

**Comment by hmason55** [comment]
Also this one has Jokers high and Aces low, I'm not sure if the Card class is supposed to be that way too. We can always change them to match if needed.

**Comment by mdoussias** [comment]
Not worth changing last minute

**Comment by mdoussias** [comment]
closign out.
