### ISSUE TITLE
Phase 3 - Need to add computer AI

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#22]
Right now it always selects the first card in the hand, need to fix this

**Comment by Mcghee-Jake** [comment]
I should add that we also need to make it so that the computer players card is removed from their hand when it is played. Right now the computer player is still pretty broken, it just repeatedly plays the same card from their hand and the hand is never updated

**Comment by hmason55** [comment]
@Mcghee-Jake yeah I noticed, I'm working on it now

**Comment by hmason55** [comment]
AI has been added.
