### ISSUE TITLE
CardTable Class

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#3]
"
The second part creates a separate CardTable class that extends JFrame. This class will control the positioning of the panels and cards of the GUI. 

Include five members:

   static int MAX_CARDS_PER_HAND = 56;
   static int MAX_PLAYERS = 2;  // for now, we only allow 2 person games
   
   private int numCardsPerHand;
   private int numPlayers;

   public JPanel pnlComputerHand, pnlHumanHand, pnlPlayArea;
 

These members are needed is to establish the grid layout for the JPanels, the organization of which depends on how many cards and players will be displayed. We'll provide an accessor, but no mutator (other than the constructor) for these members.  Here are the public instance methods:

- CardTable(String title, int numCardsPerHand, int numPlayers) - The constructor filters input, adds any panels to the JFrame, and establishes layouts according to the general description below.
- Accessors for the two instance members.

Note: We will use three Public JPanels, one for each hand (player-bottom and computer-top) and a middle "playing" JPanel.  The client (below) will generate the human's cards at random and will be visible in the bottom JPanel, while the computer's cards will be chosen (again, by the client) to be all back-of-card images in the top JPanel.  The middle JPanel will display cards that are "played" by the computer and human during the conflict.  Let's assume that each player plays one card per round, so for a 2-person game (computer + human) there will be exactly two cards played in the central region per round of battle.  My client chose a joker for the two central cards, just so we would have something to see in the playing region. 

"
**static int MAX_CARDS_PER_HAND = 56**
> - [ ] In Progress
> - [ ] Complete
      
**private int numCardsPerHand**
> - [ ] In Progress
> - [ ] Complete

**public int getNumCardsPerHand**  (Accessor)
> - [ ] In Progress
> - [ ] Complete

**private int numPlayers**
> - [ ] In Progress
> - [ ] Complete

**public int getNumPlayers** (Accessor)
> - [ ] In Progress
> - [ ] Complete

** public JPanel pnlComputerHand**
> - [ ] In Progress
> - [ ] Complete

**public JPanel pnlHumanHand**
> - [ ] In Progress
> - [ ] Complete

**public JPanel pnlPlayArea**
> - [ ] In Progress
> - [ ] Complete

**public JPanel pnlPlayArea**
> - [ ] In Progress
> - [ ] Complete

**CardTable(String title, int numCardsPerHand, int numPlayers)**
> - [ ] In Progress
> - [ ] Complete

**Comment by p12345vls** [comment]
Hunter, are you working on this class?

**Comment by hmason55** [comment]
I've just done the outline so far, nothing more in CardTable though.

**Comment by p12345vls** [comment]
Ok, I will continue with the CardTable constructor and loadCardIcons()

**Comment by p12345vls** [comment]
Phase 2, almost ready. I can continue after 8pm.

**Comment by hmason55** [comment]
@p12345vls I've updated the original comment above to match some of the other issue with check boxes included. When you get the chance could you check off the boxes that match our current progress on CardTable?
