### ISSUE TITLE
Phase 3 - Computer sometimes plays identical card twice

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#32]

**Comment by p12345vls** [comment]
It is strange but in order the computer hand not to play the same card, the newGame() call in the CardGameFramework constructor must be not there..

**Comment by p12345vls** [comment]
Wrong, disregard my previous message.

**Comment by hmason55** [comment]
This is caused by cards not being removed from the computer's hand (highCardGame.getHand(0)).
The card is still being removed from the UI via removeGUICard so that's fine for now.

**Comment by hmason55** [comment]
This is actually due to the removal of the `removeCard(int cardIndex)` method from the Hand class
It was being called previously in the `Card.playCard()` method so the removal of `Card.playCard()` method caused this bug

**Comment by p12345vls** [comment]
I dont know what it was wrong with this method but it looks now that everything works and it would be better if we can focus to the next assignment.

**Comment by Mcghee-Jake** [comment]
Oh nice. That sounds good to me. Though I think we should have someone test it out real quick before we submit. I will say that your refactoring of Phase3 in your latest pull request made it A LOT cleaner. Good job.

**Comment by Mcghee-Jake** [comment]
I just tested it and actually this bug is still there. The computer still plays the same card twice sometimes

**Comment by hmason55** [comment]
@Mcghee-Jake So the removeCard method had already been removed from our project when I implemented that code into the playCard method. The removal of the removeCard method caused the bug in the first place but since it wasn't required for the spec I added the code into playCard. Without the following code, cards don't get removed from the computer's hand when they are played which means that duplicate cards will be played.

``` // Save the card to play.
  Card playCard = myCards[cardIndex];
  
  // Remove card from hand.
  myCards[cardIndex] = null;
  
  // Store a temporary hand.
  Card[] tempHand = myCards;
  myCards = new Card[--numCards];
  int ndx = 0;
  
  // Add non-null cards from the temp hand to the persistent hand.
  for(Card card : tempHand)
  {
     if(card != null)
     {
        myCards[ndx++] = card;
     }
     
  }
```

**Comment by hmason55** [comment]
@Mcghee-Jake No, it has nothing to do with removeCard. I'm not even really sure what code was in removeCard. This code was in playCard so it would run whenever a computer played a card.

**Comment by Mcghee-Jake** [comment]
Ahhhhh! Ok damn I'm rereading the chats again and now I see what your saying. I misunderstood what you were saying about the remove card method.

**Comment by Mcghee-Jake** [comment]
Aye that seemed to work! I have no idea what changed in between last night and today but I promise I wasn't making that array out of bound error up. Maco had the same issue last night too

**Comment by hmason55** [comment]
No problem, I think we should also include our .class files from the /bin directory in the next project too because this may have caused inconsistencies in our projects

**Comment by Mcghee-Jake** [comment]
:( damn I'm getting that error again

**Comment by hmason55** [comment]
Also if you look at the module 6 playCard method in the spec, he does something similar:
```   
public Card playCard(int cardIndex)
   {
      if ( numCards == 0 ) //error
      {
         //Creates a card that does not work
         return new Card('M', Card.Suit.spades);
      }
      //Decreases numCards.
      Card card = myCards[cardIndex];
      
      numCards--;
      for(int i = cardIndex; i < numCards; i++)
      {
         myCards[i] = myCards[i+1];
      }
      
      myCards[numCards] = null;
      
      return card;
    }
```

**Comment by Mcghee-Jake** [comment]
OK yeah I think the issue is that the Human cards are never actually removed from the hand, the icon is just set to null when the JLabel is clicked.

I think we need to switch

 // remove the card from the hand
humanLabels[i].setIcon(null);
to

  // remove the card from the hand
  removeGUICard(1, card, true);
and update removeGUICard to handle the human cards. I know the code is there to handle the human cards already but I tried switching it and it isnt working quite yet.

**Comment by hmason55** [comment]
@Mcghee-Jake With your new Phase3.txt standalone, try replacing Hand.playCard with this:
```
public Card playCard(int cardIndex)
    {
        Card errorCard = new Card('w', Card.Suit.SPADES);
        if (numCards == 0 || cardIndex < 0 || cardIndex > MAX_CARDS)
            return errorCard;
       // Save the card to play.
       Card playCard = myCards[cardIndex];
       
       // Remove card from hand.
       myCards[cardIndex] = null;
       
       // Store a temporary hand.
       Card[] tempHand = myCards;
       myCards = new Card[--numCards];
       int ndx = 0;
       
       // Add non-null cards from the temp hand to the persistent hand.
       for(Card card : tempHand)
       {
          if(card != null)
          {
             myCards[ndx++] = card;
          }
         
       }
       
        return playCard;
    }
```
to and see if the out of bounds error still happens

**Comment by Mcghee-Jake** [comment]
Ok i just tried it and yeah im still getting the error

**Comment by hmason55** [comment]
@p12345vls @mdoussias Is this happening to you guys too in the standalone Phase3.txt?

**Comment by p12345vls** [comment]
With this file I am getting an error, with the previous no

**Comment by p12345vls** [comment]
The only problem with the previous is that sometimes the last played card from the computer remains in the playing area

**Comment by p12345vls** [comment]
until the next game starts

**Comment by hmason55** [comment]
@p12345vls @Mcghee-Jake Can I email you guys a zipped version of my eclipse project to try?

**Comment by p12345vls** [comment]
Sure

**Comment by mdoussias** [comment]
This was fixed, should be closed?
