### ISSUE TITLE
update Card class

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#4]
"
- [x] Adjust for the joker. (Even though there are 4 card icons, think of them as one type, X )
We need a way to know which card is higher when we compare them for the game later.  Create the following array and method(s):

- [x] public static char[] valuRanks - put the order of the card values in here with the smallest first, include 'X' for a joker
- [x] static void arraySort(Card[], int arraySize) - will sort the incoming array of cards using a bubble sort routine.  You can break this up into smaller methods if it gets over 20 lines or so.

"

**Comment by hmason55** [comment]
Closing this issue for now since the tasks are complete. After asking for permission from the professor I opted to use a quicksort algorithm rather than bubblesort for the arraySort method so you may see some extra helper methods in there. I think I've left some comments in the code labeling them.
