### ISSUE TITLE
Public, Private or package-protected

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/GUI-Cards#42]
Some methods, instance variables, and final constants might should be corrected slightly to have public or private.   

Needs a once over to make sure all is done correct.

**Comment by mdoussias** [comment]
As I finalize the diagram, I will check for this.  However, it's a lot.  So after the UML is made if anyone sees anything, please note here or put a pull request to fix.

I don't want to change a lot last minute for fear of making a bug.... I will record any functions I intend to fix here for easy traceability and/or discussion.

**Comment by p12345vls** [comment]
I will try to add a button to restart the game, I am not sure if the time is enough to do this..

**Comment by mdoussias** [comment]
Closing this issue out because it is a duplicate
