### ISSUE TITLE
Missing Notes phase 3

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/GUI-Cards#46]
Phase3 has several methods with missing notes.  
Might be best to add if time permits.

**Comment by mdoussias** [comment]
I'm focusing on my other assigned issues for now, because they're more important, but I will come back and assign myself to this if time permits.

**Comment by p12345vls** [comment]
That's right, we will do this it is necessary

**Comment by mdoussias** [comment]
This still needs done.
First I will finish the other stuff and then come back to this.

**Comment by mdoussias** [comment]
Looks mostly done.  I'm going to leave it. 

Probably could use some notes for variables.... but I don't want to put erroneous notes.
