### ISSUE TITLE
CARD, DECK, HAND class all needs combined in each phaseN.txt file

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/GUI-Cards#48]
- [x] Compile the HAND,DECK and CARD class into one file

- [x]  Add to PHase1
- [x]  Add to PHase2
- [x]  Add to PHase3

**Comment by p12345vls** [comment]
I will do it

**Comment by mdoussias** [comment]
Cool... I'll work on something else

Pavlos.... the below also need fixed to be either private or public:
They are in either the Hand, Deck or Card class.... I can't remember which one and they are not explicitly stated as private or public

? arraySort(Card[] cards, int arraySize) : void

? getSortRanking(Card card) : int

**Comment by p12345vls** [comment]
both public

**Comment by mdoussias** [comment]
This was completed.  Closing out.
