### ISSUE TITLE
GUICard Class

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#5]
"

The second part creates a separate CardTable class that extends JFrame. This class will control the positioning of the panels and cards of the GUI. ...

This class is the benefactor of most of the GUI machinery we tested in Phase 1. It will read the image files and store them in a static Icon array. Rather than a 1-D array of Phase 1, this will be a 2-D array to facilitate addressing the value and suit of a Card in order get its Icon. While simple in principle (just read the Icons and store them in an array for client use), the details are subtle. We have to be able to convert from chars and suits to ints, and back again, in order to find the Icon for any given Card object. The overview of the class data and methods, shown below, will suggest the right approach and should take the mystery out of this class.

Include three members:

 -  private static Icon[][] iconCards = new ImageIcon[14][4]; // 14 = A thru K + joker
-  private static Icon iconBack;
 - static boolean iconsLoaded = false;
The 52 + 4 jokers Icons will be read and stored into the iconCards[][] array.  The card-back image in the iconBack member.  None of these data need to be stored more than once, so this is a class without instance data.  This class is used is to produce an image icon when the client needs one. 

To begin, we need a method that generates the image Icon array from files:

- static void loadCardIcons() - the code for this was fundamentally done in Phase 1.  The difference here is that we are storing the Icons in a 2-D array.  Don't require the client to call this method.  Think about where you would need to call it and how can you avoid having the method reload the icons after it has already loaded them once.  Hint:  Call this method any time you might need an Icon, but make sure that it loads the entire array the first time it is called, and does nothing any later time.
The primary public method offered by this class:

- static public Icon getIcon(Card card) - This method takes a Card object from the client, and returns the Icon for that card.  It would be used when the client needs to instantiate or change a JLabel. It can return something like:
return iconCards[valueAsInt(card)][suitAsInt(card)];
There is another method that returns the card-back image:

- static public Icon getBackCardIcon() - this one is even simpler than getIcon().
The above three methods comprise the essential part of the GUICard class.  Everything else is support for these three, so you can work off my implied suggestions, or you can build the class from scratch as you wish.  Just make sure you are efficient.

**private static Icon[][] iconCards = new ImageIcon[14][4]** (14 = A thru K + joker)
> - [ ] In Progress
> - [ ] Completed

**private static Icon iconBack**
> - [ ] In Progress
> - [ ] Completed

**static boolean iconsLoaded = false**
> - [ ] In Progress
> - [ ] Completed

**static void loadCardIcons()**
> - [ ] In Progress
> - [ ] Completed

**static public Icon getIcon(Card card)** (return iconCards[valueAsInt(card)][suitAsInt(card)])
> - [ ] In Progress
> - [ ] Completed

**static public Icon getBackCardIcon()**
> - [ ] In Progress
> - [ ] Completed

**Comment by p12345vls** [comment]
Ok I see, the class CardTable and GUICard are in the Phase2.java class. If you are not working on **loadCardIcons()** and **CardTable** constructor please let me know.
