### ISSUE TITLE
Running Phase3.java by itself only generates 3 GUI cards in the player's hand.

### ISSUE THREAD

**Issue by hmason55** [team-makeSmart/GUI-Cards#61]
The hand object is fine though and in the console it displays 7 cards, but the GUI only shows 3 in the player's hand. Again, this happened when I created a new Java file from Phase3.txt to run as a standalone.

**Comment by Mcghee-Jake** [comment]
Yeah I think the issue is that the Human cards are never actually removed from the hand, the icon is just set to null when the JLabel is clicked.

I tried switching 

     // remove the card from the hand
    humanLabels[i].setIcon(null);

to 

      // remove the card from the hand
      removeGUICard(1, card, true);

and update removeGUICard to handle the human cards. I know the code is there to handle the human cards already but I tried switching it and I wasn't able to get it to work.

**Comment by p12345vls** [comment]
I created now a new project and a new file, copy pasted the Phase3.txt and it works

**Comment by p12345vls** [comment]
The last updated file is the  **Phase3.txt** the Phase3.java has not be updated

**Comment by p12345vls** [comment]
I am missing something? We need to submit a .txt file or not?

**Comment by hmason55** [comment]
yeah, I made a seperate Phase3.java in a new project using Phase3.txt and that's what happened.

**Comment by hmason55** [comment]
No we do, I'm just testing it to make sure everything works

**Comment by Mcghee-Jake** [comment]
Yeah brand new project, Just a single class Phase3 copied over from Phase3.txt

I've recreated the current Phas3.txt project from scratch multiple times today on two different machines and haven't encountered this error so I think the issue may be something on your end?

Can you try recreating the project from scratch again? Completely delete your Gui-Cards folder and clone the project again just in case

**Comment by hmason55** [comment]
@Mcghee-Jake My bad, I actually missed a few card images when doing that.

**Comment by Mcghee-Jake** [comment]
No worries
