### ISSUE TITLE
PHASE3    Unused instance arrays in 

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/GUI-Cards#66]
Whatever changes were made to the program, these variables are no longer used..... Should we delete from phase 3?  Will affect UML.

- [x]   private static JLabel[] playLabelText = new JLabel[NUM_PLAYERS];

- [x]   private static JLabel[] scoreTextLabel = new JLabel[NUM_PLAYERS];

**Comment by p12345vls** [comment]
They can be deleted

**Comment by mdoussias** [comment]
I just put a pull request.
