### ISSUE TITLE
update Deck class

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#7]
- [x] Adjust for the joker in the MasterPack.
Add methods for adding and removing cards from the deck as well as a sort method. (these will be using in the CardGameFramework given in Phase 3)

- [x] boolean addCard(Card card) - make sure that there are not too many instances of the card in the deck if you add it.  Return false if there will be too many.  It should put the card on the top of the deck.
- [x] boolean removeCard(Card card) - you are looking to remove a specific card from the deck.  Put the current top card into its place.  Be sure the card you need is actually still in the deck, if not return false.
- [x] void sort() - put all of the cards in the deck back into the right order according to their values.  Is there another method somewhere that already does this that you could refer to?
- [x] int getNumCards() - return the number of cards remaining in the deck.

**Comment by p12345vls** [comment]
Working on **addCard(Card card)** and **removeCard(Card card)**
