### ISSUE TITLE
update Main class (from Assignment 3)

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#8]
You will also need a method that will give you a random new card.  It is a main class method.  

- static Card generateRandomCard() - returns a new random card for the main to use in its tests.

**Comment by mdoussias** [comment]
I will work on this friday night.

**Comment by mdoussias** [comment]
I have this.... Not sure exactly where to put it?  In the main class of phase 2?   


/**
    * Generates and returns a card with a random suit and random values
    * 
    * @returns a newly generated random card object
    */
   public static Card generateRandomCard()
   {
      // Generate a random integer that will be a valid index value of the
      // array Card.VALID_CARD_VALUES
      int cardIndex = (int) (Math.random() * Card.VALID_CARD_VALUES.length);

      // Get char value at index of array and store in char cardValue
      char cardValue = Card.VALID_CARD_VALUES[cardIndex];

      // Generate a random number that will be associated with suit of a card
      int suitIndex = (int) (Math.random() * 4);

      // Generate and return a Card object
      if (suitIndex == 0)
      {
         return new Card(cardValue, Card.Suit.CLUBS);
      } else if (suitIndex == 1)
      {
         return new Card(cardValue, Card.Suit.HEARTS);
      } else if (suitIndex == 2)
      {
         return new Card(cardValue, Card.Suit.SPADES);
      } else
      {
         return new Card(cardValue, Card.Suit.DIAMONDS);
      }

   }

**Comment by mdoussias** [comment]
Method was made and put into phase 2... But as of this writing was not used in Phase2
